# docker-compose.yml file version
version: '2'


# Services (Docker containers)
services:

  # Mongo Database service
  mongodb:
    # Give it a name 
    container_name: mongodb_container

    ports:
      - "27017:27017"
 
    image: mongo:latest
    # We use mongostorage data volume and we will use the /data/db path for the database inside the container
    volumes: 
      - ./data/mongodb:/data/db



  # REST API service
  restapi:
    # Build image from jar
    build: .
    # Give it a name
    container_name: restapi_container
    # The port that our API will have exposed so we can connect to
    ports:
      - "8080:8080"

    links:
      - mongodb:mongodb


  # Web service
  frontend:
    # Give it a name
    container_name: nginx_container

    image: nginx:alpine

    volumes:
      - ./web:/usr/share/nginx/html

    ports:
      - "80:80"
      - "443:443"
